// Generated by CoffeeScript 1.3.3
(function() {
  var Client, Repository, TreeStore, app, assert, backend, client1, client2, contentAddressable, createApp, createMemoryStore, dataA, dataB, difference, req, serverBlobStore, serverHeadStore, serverRepo, serverTreeStore, testPort, url, _ref;

  assert = require('assert');

  req = require('superagent');

  _ref = require('synclib'), Repository = _ref.Repository, TreeStore = _ref.TreeStore, backend = _ref.backend;

  contentAddressable = require('content-addressable');

  createMemoryStore = require('pluggable-store').server().memory;

  createApp = require('../lib/index');

  difference = require('underscore').difference;

  testPort = 3000;

  url = function(path) {
    return 'http://localhost:' + testPort + path;
  };

  serverBlobStore = contentAddressable.fileSystem(process.env.HOME + '/syncstore');

  serverTreeStore = contentAddressable.memory();

  serverHeadStore = createMemoryStore();

  serverRepo = new Repository(serverTreeStore);

  app = createApp({
    blobStore: serverBlobStore,
    repository: serverRepo,
    headStore: serverHeadStore
  });

  Client = (function() {

    function Client() {
      this.blobStore = contentAddressable.memory();
      this.treeStore = contentAddressable.memory();
      this.repo = new Repository(this.treeStore);
      this.branch = this.repo.branch();
      this.remotes = {};
    }

    return Client;

  })();

  client1 = new Client();

  client2 = new Client();

  dataA = [
    {
      'a': "hashA 0.0",
      'b/c': "hashA 0.1",
      'b/d': "hashA 0.2"
    }, {
      'a': "hashA 1.0",
      'b/c': "hashA 1.1",
      'b/e': "hashA 1.2",
      'b/f/g': "hashA 1.3"
    }, {
      'b/e': "hashA 2.0"
    }
  ];

  dataB = [
    {
      'b/h': "hashB 0.0"
    }, {
      'c/a': "hashB 1.0"
    }, {
      'a': "hashB 2.0",
      'u': "hashB 2.1"
    }, {
      'b/c': "hashB 3.0",
      'b/e': "hashB 3.1",
      'b/f/a': "hashB 3.2"
    }
  ];

  before(function(done) {
    return app.listen(testPort, 'localhost', done);
  });

  after(function(done) {
    return serverBlobStore.store.adapter["delete"](done);
  });

  describe('http-interface', function() {
    describe('blob storage', function() {
      return it('should POST some data and return the hash to GET it', function(done) {
        var data;
        data = {
          data: "some data"
        };
        return req.post(url('/blob')).send(data).end(function(res) {
          var hash;
          hash = res.body.hash;
          return req.get(url('/blob/' + hash)).end(function(res) {
            assert.equal(res.body.data, data.data);
            return done();
          });
        });
      });
    });
    describe('client1', function() {
      it('should do some local commits and POST the diff to the server', function(done) {
        var diff, diffHashs, each, _i, _len;
        for (_i = 0, _len = dataA.length; _i < _len; _i++) {
          each = dataA[_i];
          client1.branch.commit(each);
        }
        diffHashs = client1.branch.patchHashs();
        diff = client1.repo.patchData(diffHashs);
        return req.post(url('/trees')).send(diff.trees).end(function(res) {
          var i, _j, _len1, _ref1;
          _ref1 = res.body.treeHashs;
          for (i = _j = 0, _len1 = _ref1.length; _j < _len1; i = ++_j) {
            each = _ref1[i];
            assert.equal(each, diffHashs.trees[i]);
          }
          return done();
        });
      });
      return it('should set its head on the server', function(done) {
        return req.put(url('/head/client1')).send({
          hash: client1.branch.head
        }).end(function(res) {
          return req.get(url('/head/client1')).end(function(res) {
            assert.equal(res.body.hash, client1.branch.head);
            return done();
          });
        });
      });
    });
    return describe('client2', function() {
      it('should do some commits and push the diff', function(done) {
        var diff, each, _i, _len;
        for (_i = 0, _len = dataB.length; _i < _len; _i++) {
          each = dataB[_i];
          client2.branch.commit(each);
        }
        diff = client2.repo.patchData(client2.branch.patchHashs());
        return req.post(url('/trees')).send(diff.trees).end(function() {
          return done();
        });
      });
      it('should ask for client1\'s head and the common commit', function(done) {
        return req.get(url('/head/client1')).end(function(res) {
          client2.remotes.client1 = res.body.hash;
          return req.get(url('/common-tree?tree1=' + client2.branch.head + '&tree2=' + client2.remotes.client1)).end(function(res) {
            assert.equal(res.commonTree, null);
            return done();
          });
        });
      });
      it('should ask for the full diff to client1 head since there is no common tree', function(done) {
        return req.get(url('/trees?to=' + client2.remotes.client1)).end(function(res) {
          client2.treeStore.writeAll(res.body.trees);
          return done();
        });
      });
      it('should do a local merge of client1s diff', function() {
        var head, headTree, oldHead;
        oldHead = client2.branch.head;
        head = client2.branch.merge({
          ref: client2.remotes.client1
        });
        headTree = client2.treeStore.read(head);
        return assert.equal(difference(headTree.ancestors, [client2.remotes.client1, oldHead]).length, 0);
      });
      return it('should push its new diff to the server', function() {
        /*
              this is trickier than I thought:
              diff1 = the diff between my last push and my current head
              this includes redundant information
              diff2 = diff between my last push and client1 head
              diff to be pushed = diff1 - diff2
              right?
              I should update my local remotes only after having pulled the diff
              then I can use it to compute diff2 safely - otherwise I might lack data
              if we consider a multi-master setup its more complex:
                I would have to check if the servers remote head is more or less advanced
                the safest way is to always first do a pull - but we also dont want to waste time to do pushs...
                if the server has an ancestor of my client1 head:
                  its simple - we just use the servers client1 head to compute diff2
                if the server is further than my client1 head:
                  we just use our local one to push
                if the server is on a fork
                  we first have to find out that he is - by doing a common-tree call
                maybe thats always the best thing to do - call common-tree to find out what to use as client1 head
                I have to think about this - especially on how to scale this to many peers.
                I might have to rewrite branch.patch to let me compute a patch for multiple branches.
        */

      });
    });
  });

}).call(this);
