// Generated by CoffeeScript 1.3.3
(function() {
  var Repository, TreeStore, async, backend, contentAddressable, createApp, express, _, _ref;

  _ref = require('synclib'), Repository = _ref.Repository, TreeStore = _ref.TreeStore, backend = _ref.backend;

  contentAddressable = require('content-addressable');

  express = require('express');

  _ = require('underscore');

  async = require('async');

  createApp = function(_arg) {
    var app, blobStore, repository;
    blobStore = _arg.blobStore, repository = _arg.repository;
    app = express();
    app.configure(function() {
      app.use(express.cookieParser());
      app.use(express.cookieSession({
        secret: 'SyncStore'
      }));
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      return app.use(app.router);
    });
    app.configure('development', function() {
      return app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
    });
    app.configure('production', function() {
      return app.use(express.errorHandler());
    });
    app.get('/', function(req, res) {
      return res.send({
        ok: 'SyncStore is running'
      });
    });
    app.get('/changes', function(req, res) {});
    app.get('/common-tree', function(req, res) {});
    app.get('/trees', function(req, res) {});
    app.post('/trees', function(req, res) {});
    app.put('/head/:branch', function(req, res) {});
    app.get('/head/:branch', function(req, res) {});
    app.post('/blob', function(req, res) {});
    return app.get('/blob/:hash', function(req, res) {});
  };

  module.exports = createApp;

}).call(this);
