// Generated by CoffeeScript 1.3.3
(function() {
  var async, createApp, express, _;

  express = require('express');

  _ = require('underscore');

  async = require('async');

  createApp = function(_arg) {
    var app, blobStore, headStore, repository;
    blobStore = _arg.blobStore, repository = _arg.repository, headStore = _arg.headStore;
    app = express();
    app.configure(function() {
      app.use(express.cookieParser());
      app.use(express.cookieSession({
        secret: 'SyncStore'
      }));
      app.use(express.bodyParser());
      app.use(express.methodOverride());
      return app.use(app.router);
    });
    app.configure('development', function() {
      return app.use(express.errorHandler({
        dumpExceptions: true,
        showStack: true
      }));
    });
    app.configure('production', function() {
      return app.use(express.errorHandler());
    });
    app.get('/', function(req, res) {
      return res.send({
        ok: 'SyncStore is running'
      });
    });
    app.get('/changes', function(req, res) {});
    app.get('/common-tree', function(req, res) {});
    app.get('/trees', function(req, res) {});
    app.post('/trees', function(req, res) {
      return repository.store.writeAll(req.body, function(err, hashs) {
        return res.send({
          treeHashs: hashs
        });
      });
    });
    app.put('/head/:branch', function(req, res) {
      headStore.write(req.params.branch, req.body.hash);
      return res.send({
        ok: 'success'
      });
    });
    app.get('/head/:branch', function(req, res) {
      return res.send({
        hash: headStore.read(req.params.branch)
      });
    });
    app.post('/blob', function(req, res) {
      return blobStore.write(JSON.stringify(req.body), function(err, hash) {
        return res.send({
          hash: hash
        });
      });
    });
    app.get('/blob/:hash', function(req, res) {
      return blobStore.read(req.params.hash, function(err, data) {
        return res.send(JSON.parse(data));
      });
    });
    return app;
  };

  module.exports = createApp;

}).call(this);
